route:
  ip: '0.0.0.0/32'
  gateway: '10.7.5.1'
  dev: 'eth0'

docker:
  execute:
      network: "global-testbed_leotest-net"
      volume:
        source: "/datadrive1/leoscope/jobs" 
        dest: "/artifacts"