name: Docker Image CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "1 0 * * 4"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    # - name: Build the Docker image
    #   run: docker build . --file ./docker/orchestrator/Dockerfile --tag orchestrator-img-auto:$(date +%s)
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Orchestrator
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: projectleopard/orchestrator-img-auto:latest
        file: ./docker/orchestrator/Dockerfile

    - name: Build and push Node
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: projectleopard/node-img-auto:latest
        file: ./docker/node/Dockerfile
